### ISSUE TITLE
Daycare affiliation

### ISSUE THREAD

**Issue by arthurgustin** [Vinubaba/SANTC-API#7]
Currently, the backend application works as if there was only 1 "global" daycare.
Users are parent/teacher/officeManager and admin.
There is also the kid entity.

What we need now is to affiliate a user to a specific daycare in order to "logically" separate user views in the frontend. e.g:

  - An office manager cannot see kids/classes/parents/teachers of another daycare
  - A teacher cannot see kids/classes/parents/teachers of another daycare
  - An adult cannot see classes of another daycare

Same for food, activities, etc...

From there, 2 possibilities:

  1) Add a new entity called "daycare", and every users (office managers included) will be tagged as "daycare X member"
  2) Simpler: Use the office manager ID to do the same.

**Comment by arthurgustin** [comment]
@Vinubaba any thoughts on this ? What if the daycare owner change, we will need to manage that. Maybe an office-manager could have a button for granting OM rights to someone else.

**Comment by Vinubaba** [comment]
@arthurgustin I think the new entity should be location, as there can be many daycares with the same name but not the same address. Address in usa = address line 1, 2, city, state, zip code. 
I think granting rights is a different issue , we will need it but not for MVP. right now focus on just getting the critical pieces done. if you just want to work on the backend, let me know your estimate and we can give the front to thew nepal guy and hope he does a good job. can you give me an estimate so that we dont lose him?

**Comment by arthurgustin** [comment]
Well I think I've done enough for a starter app, my hope is that Tsering can iterate and improve my work.
In order to finish this registration workflow, I need to implement those backend features: #8 #12 #13 #14 
I created issues in the OM-APP, so tsering can know where to begin once he gets the code.

**Comment by Vinubaba** [comment]
OK thanks, let me know when you send him a message please,,,,

Regards,

Vinu Singh
972-523-0729

**Comment by arthurgustin** [comment]
Ok so if 1 daycare can have several locations, I need to know what they can share or what they can't.

  - Can a teacher teaches in several locations ?
  - Can a kid go in several locations ?
  - Are there 1 office manager per locations or 1 office manager can work or manage several locations ?

**Comment by Vinubaba** [comment]
no to all your questions.
and one OM for a fixed location only.

thanks
