### ISSUE TITLE
Support for kid age range

### ISSUE THREAD

**Issue by arthurgustin** [Vinubaba/SANTC-API#8]

**Comment by Vinubaba** [comment]
we decided to keep it free form, which means its just text boxes. OM can
define an age range and give it a name. do you need a screenshot?

**Comment by arthurgustin** [comment]
Yes it would be helpful !
I think that defining a new age range should not be inside the registration form, but rather in an option panel or something. In the registration page, the user should be able to chose between the age range he already defined. Or even better: if we know that a age range correspond to 3-5 years old, it can be magically performed on the server side thanks to the birth date

**Comment by Vinubaba** [comment]
It's on a class page where classes are defined. So if you're adding a
student, it will appear and should get selected based on birth date. We
need to move classes to be first tab so that a class is defined first. Not
code class, but classroom. So I'm will define get this class is fkr this
age range and I call the age range as infant for example and my class name
is giraffes.

**Comment by arthurgustin** [comment]
Ok so maybe I should implement classes first, because I have the feeling this issue depends on #13

**Comment by Vinubaba** [comment]
What's 13. I can't see git right now.

**Comment by arthurgustin** [comment]
#13 is the daycare classes feature

**Comment by Vinubaba** [comment]
Yes makes sense then. Just remember all age ranges and range name is text
boxes free form.

**Comment by arthurgustin** [comment]
Well for the range, I would rather set min and max limit like the following:
Age range = (name, age min, age max)
name is text, age min and age max are numbers

**Comment by Vinubaba** [comment]
Give me some time I will send screenshot.

**Comment by Vinubaba** [comment]
You should have my axure cloud link right. Why don't you go there and see
it. It's not sketch. It's axure. Axshare.

**Comment by Vinubaba** [comment]
Check your email

**Comment by Vinubaba** [comment]
Yeah that's a qa issue but it's obvious.

**Comment by arthurgustin** [comment]
It's not obvious when you say free text, because text means text, it could be a drop down list or a counter with arrows. Anyway, for frontends stories, I think that text constaints should be part of the spec, it will be clearer for everyone

**Comment by Vinubaba** [comment]
Haha well it's cultural issue. Free text means free input text. Direct
input verus a drop down which is not something you can type. No worries.

**Comment by arthurgustin** [comment]
Hey Vinu, I looked at the axshare one more time and I have others questions:
  - Is 1 class = 1 age range or they could be several classes with the same age range
  - Should we register a kid only to an existing class instead of age range + class? To me it makes more sense. I have the feeling that specifying kid's birth date and kid's age range is a double information. And for the office manager it's maybe simpler to chose only a class ?

The dropdown list for classes could be automatically updated, based on birthdate ? And if there are none we could assign a child to class later ?

**Comment by Vinubaba** [comment]
@arthurgustin 
- there could be many classes with the same age range, depending on the size of the business. its not a 1 - 1 thing. 
- we are not registering a child to an age range, we are simply asking the OM to make sure the class is the right one for the child using the age range. the class name should be d=selected for OM using the birthdate automatically as well as the age range. in case there are multiple claasses, they should be asked to select one - but only from the the right clsses - e.g. it doesnt make sense to ask them to select from 5 classes if only 2 of them are the right ones. the OM will not be select an age range, they will simply verify its the right one - its visual feedback. they should not be able to change the age range unless the birthdate is changed.

 I am not able to remember but I am hoping that the class definition has months and years for each range., ir.e from age and to age - because we need to make sure that when they enter this info, they can specify if the number is in months or years and same for the maximum age for that class, so they dont have to manually convert months to years or vice versa. its a small thing but its more user friendly and convenient to the OM. also the screen to define a class should be visually shown before adding the kids task in the tabs. otherwise they cant assign a child to a class and they will have to go back to adding a class first. i will make the change in the sketch mockups.

**Comment by arthurgustin** [comment]
Ok then, for the second point, the age-range information could be shown directly in the drop down list no ? Or right after but not in a dropdown list, just text, but I get the point.
In my backend, classes and age range will be separated entities if you say we can have 1 - N relationship between classes and age range. For instance, an OM could create 1 age range for 1 - 3 years called toto, and create 4 classes with the age range toto. For the classes, it should be able to chose amongst existing age range or create a new one, do you agree ?

**Comment by Vinubaba** [comment]
We are not creating classes in this page . we are enrolling kids and parents info. If a new class is needed they would need tobgobto the classes page. As far as age range is concerned yes it could be just text but I think we should keep it open ended. What if I'm doesn't know birthdate or wants to put in a different age group because their birthdays is so close to the next age range.

**Comment by Vinubaba** [comment]
Mobile website of github doesn't let me tag you

**Comment by Vinubaba** [comment]
Class name should be unique. Can't have 4 classes with same name.

**Comment by arthurgustin** [comment]
> Class name should be unique. Can't have 4 classes with same name.

Yes I know that

> Mobile website of github doesn't let me tag you

Why do you want to tag me lol

> We are not creating classes in this page . we are enrolling kids and parents info. If a new class is needed they would need tobgobto the classes page. As far as age range is concerned yes it could be just text but I think we should keep it open ended. What if I'm doesn't know birthdate or wants to put in a different age group because their birthdays is so close to the next age range.

Well in this  case you can chose another class, not another age range, since age range is displayed as part of the class information. And if a parent does not know the birthdate of his child it's another problem...

**Comment by Vinubaba** [comment]
what is the issue here? why cant the user select another class or age range
and it just updates? not sure i understand how and why this impacts the
backend?

**Comment by arthurgustin** [comment]
What I ask is: is it possible to simplify this form by having only 1 dropdown list for class. In this list, we can display the age range like this:

  - Mickey ( 9 month - 16 month)
  - Dingo (1 year - 2 year)
  - Pluto (2 year - 3 year)

I don't want the age range to be a distinct information.

**Comment by Vinubaba** [comment]
Thats what I am trying to ask you. Why? why cant age range be distinct? the
OM mental model can be various - she can think via age range, or class or
even growth stage and then the system shows her the appropriate selects she
has not made in the other areas.  are you saying this will honestly cause
you trouble or more work in back end? also your example doesnt show growth
stage - example toddler.

Regards,

Vinu Singh
972-523-0729

**Comment by arthurgustin** [comment]
Same work for me, it just feel not normal to me, that's why I ask you, but nevermind then we go as you say :)

**Comment by Vinubaba** [comment]
We can ask this for usability testing but I think the more freedom we give,
the more it will be appreciated. Unless of course we dont know how to do
something or it will take too long for MVP or if you say this will be huge
effort in backend.

Regards,

Vinu Singh
972-523-0729
